INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (1, 10265, 'Clean Code', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1323/9780132350884.jpg', 'Even bad code can function. But if code isn''t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn''t have to be that way.');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (1, 303, 'Paperback', 'Robert Martin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (2, 8735, 'Clean Architecture', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1344/9780134494166.jpg', 'Building upon the success of best-sellers The Clean Coder and Clean Code, legendary software craftsman Robert C. "Uncle Bob" Martin shows how to bring greater professionalism and discipline to application architecture and design.');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (2, 329, 'Robert Martin', 'Robert Martin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (3, 9693, 'Clean Coder', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1370/9780137081073.jpg', 'Programmers who endure and succeed amidst swirling uncertainty and nonstop pressure share a common attribute: They care deeply about the practice of creating software. They treat it as a craft. They are professionals.
');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (3, 17, 'Paperback', 'Robert Martin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (4, 8915, 'Clean Agile', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1357/9780135781869.jpg', 'Agile Values and Principles for a New Generation
"In the journey to all things Agile, Uncle Bob has been there, done that, and has the both the t-shirt and the scars to show for it. This delightful book is part history, part personal stories, and all wisdom. If you want to understand what Agile is and how it came to be, this is the book for you."
-Grady Booch');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (4, 484, 'Paperback', 'Robert Martin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (5, 11283, 'Clean Craftsmanship', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1369/9780136915713.jpg', 'ow to Write Code You''re Proud of . . . Every Single Day
". . . [A] timely and humble reminder of the ever-increasing complexity of our programmatic world and how we owe it to the legacy of humankind--and to ourselves--to practice ethical development. Take your time reading Clean Craftsmanship. . . . Keep this book on your go-to bookshelf. Let this book be your old friend--your Uncle Bob, your guide--as you make your way through this world with curiosity and courage."
--From the Foreword by Stacia Heimgartner Viscardi, CST & Agile Mentor');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (5, 249, 'Paperback', 'Robert Martin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (6, 18836, 'Refactoring', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1347/9780134757599.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (6, 200, 'Hardback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (7, 21975, 'Patterns of Enterprise Application Architecture', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3211/9780321127426.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (7, 287, 'Hardback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (8, 15696, 'UML Distilled', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3211/9780321193681.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (8, 229, 'Paperback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (9, 18836, 'Domain-Specific Languages', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3217/9780321712943.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (9, 137, 'Hardback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (10, 12556, 'User Story Mapping', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/4919/9781491904909.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (10, 112, 'Paperback', 'Jeff Patton');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (11, 14126, 'NoSQL Distilled', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3218/9780321826626.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (11, 62, 'Paperback', 'Pramod Sadalage');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (12, 14126, 'Refactoring', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/2014/9780201485677.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (12, 179, 'Hardback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (13, 17266, 'Refactoring', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3219/9780321984135.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (13, 407, 'Paperback', 'Jay Fields');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (14, 25746, 'Advanced Object-Oriented Analysis and Design Using UML', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/5216/9780521648196.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (14, 214, 'Paperback', 'James J. Odell');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (15, 25746, 'Refaktoryzacja', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9788/3283/9788328355637.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (15, 50, 'Paperback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (16, 25746, 'Lines of the Times', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/9259/9781925949957.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (16, 131, 'Paperback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (17, 25746, 'You Always Belonged and You Always Will', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/6159/9780615931326.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (17, 313, 'Paperback', 'Martin Clay Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (18, 25746, 'John Fowler', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/7112/9780711227118.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (18, 370, 'Hardback', 'Martin Wood');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (19, 25746, 'Analysis Patterns', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1341/9780134186054.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (19, 177, 'Paperback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (20, 25746, 'Refaktoryzacja Ulepszanie struktury istniejącego kodu', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9788/3246/9788324632435.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (20, 346, 'Hardback', 'John Brant');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (21, 25746, 'Refactoring', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9783/9584/9783958459410.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (21, 197, 'Paperback', 'Martin Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (22, 25746, 'Planning Extreme Programming', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/2017/9780201710915.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (22, 400, 'Paperback', 'Kent Beck');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (23, 25746, 'Refactoring', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/3216/9780321603500.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (23, 220, 'Hardback', 'Jay Fields');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (24, 25746, 'Martin Hussingtree saves Liverpool!', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/5397/9781539706793.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (24, 53, 'Paperback', 'John Michael Fowler');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (25, 9416, 'The Gospel of Education', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/9520/9781952025419.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (25, 421, 'Paperback', 'Martin Zschoche');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (26, 9416, 'Readers, Texts and Compilers in the Earlier Middle Ages', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/7546/9780754662358.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (26, 150, 'Hardback', 'Martin Brett');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (27, 9416, 'Prevention of Cardiovascular Disease', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/1926/9780192623973.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (27, 363, 'Paperback', 'Martin Lawrence');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (28, 9416, 'Lectures on Localization in Diseases of the Brain', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/3403/9781340389925.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (28, 259, 'Hardback', 'Dr Jean Martin Charcot');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (29, 9416, 'Improving Learning in College', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9780/4154/9780415469128.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (29, 73, 'Paperback', 'Roz Ivanic');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, LANGUAGE, IMAGEURL, DESCRIPTION) VALUES (30, 10672, 'Readers, Texts and Compilers in the Earlier Middle Ages', 'Programming', '2020-02-19', 'English', 'https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/1382/9781138257313.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Velit aliquet sagittis id consectetur purus ut. ');
INSERT INTO WOLF.BOOK (ID, PAGENUMBER, TYPE, AUTHOR) VALUES (30, 318, 'Paperback', 'Martin Brett');

