INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (31, 1795, 'Smells Like Teen Spirit', 'Jazz', '', 'https://img.youtube.com/vi/hTWKbfoikeg/0.jpg', 'Starting off we have “Smells Like Teen Spirit”, which was written by the late Kurt Cobain, Krist Novoselic, and Dave Grohl. Performed by the famous and legendary band Nirvana (founded in 1987), this song became part of the top songs of the 1990s. Released in September of 1991, “Smells Like Teen Spirit” took the #1 spot on the Billboard’s Alternative Songs Chart. It is now one of the few songs that have gotten a whopping 1 billion views on YouTube.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (31, '2:54', 'Nirvana');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (32, 1377, 'Billie Jean', 'Classical', '', 'https://img.youtube.com/vi/Zi_XLOBDo_Y/0.jpg', 'Going to #2 we have “Billie Jean” by the loved and missed Michael Jackson. Jackson released “Billie Jean” in his iconic album Thriller. Released by Epic Records in 1982, Thriller has now been certified as 34x platinum, which means this album sold more than 34 million times. Other popular songs from Michael Jackson’s Thriller include “P.Y.T.”, “Beat It,” and “Thriller.”');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (32, '1:21', 'Michael Jackson');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (33, 1940, 'Stayin’ Alive', 'Classical', '', 'https://img.youtube.com/vi/fNFzfwLM72c/0.jpg', 'Heading over to the disco era of America, #3 on this list is Stayin’ Alive by the Bee Gees. Released in 1977, “Stayin’ Alive” peaked at #28 on the billboards and stayed on the charts for 13 weeks. This song is most famously known from the 1977 movie Saturday Night Fever, which stars John Travolta. An album with only one song on it, The Bee Gees was still able to pull platinum on it, selling more than 3 million copies.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (33, '1:11', 'Bee Gees');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (34, 274, 'I Will Survive', 'Classical', '', 'https://img.youtube.com/vi/FHhZPp08s74/0.jpg', 'One of the most beloved and well-known songs of all time, repeated by artists like Cake and Demi Lovato, coming down next to the best playlist of all time is Gloria Gaynor’s “I Will Survive.” Released in 1978 on her album Love Tracks, “I Will Survive” tells the story of being able to move on after a bad relationship. Originally written by Freddie Perren and Dino Fekaris, Gloria Gaynor ended up singing this song because her record company called Perren to see if they had any songs for them.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (34, '1:2', 'Gloria Gaynor');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (35, 207, 'Whole Lotta Love', 'New era', '', 'https://img.youtube.com/vi/HQmmM_qwG4k/0.jpg', 'One of the most well-known bands to date, Led Zeppelin with their song “Whole Lotta Love” created a whirlpool of fanaticism at the height of their popularity. “Whole Lotta Love” came out in 1969 and was featured in the movie ‘The Song Remains the Same.’ An interesting fact about Led Zeppelin and how they got their name: one time while performing as the New Yardbirds, there were conversations about them saying they would “go down like a lead balloon.” From then on they named themselves Led Zeppelin and have become a household name that almost everyone knows.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (35, '2:17', 'Led Zeppelin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (36, 1207, 'Sweet Child O’Mine', 'Classical', '', 'https://img.youtube.com/vi/1w7OgIMMRc4/0.jpg', 'If you have heard of the band Guns N’ Roses before, I am willing to bet money you have heard “Sweet Child O’Mine” before. From their album Appetite for Destruction in 1987, “Sweet Child O’Mine” has won several awards, including the MTV Video Music Award for Best Rock Video and the American Music Award for Favorite Pop/Rock Single. This song was so popular in 1988 that it hit the #1 spot on the charts. If you have never listened to this song, I encourage you to get your rock on.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (36, '2:46', 'Guns N’ Roses');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (37, 1194, 'Scream and Shout', 'New era', '', 'https://img.youtube.com/vi/J9W-_W50ChE/0.jpg', 'Going into a more modern-age song, released in 2012 coming in on this list is a song by Will.I.Am and Brittney Spears, “Scream and Shout.” A common sound now used on social media for their intro which ends in “bring the action,” “Scream and Shout” reached the #1 spot on the US Hot Dance/Electronic Songs Billboard. Not only that but “Scream and Shout” hit the #1 spot in 29 different countries around the world. This is a perfect song to party to and jam out to. Whether you are hanging out with friends, creating a social media post, or working out at the gym, you should check out “Scream and Shout” and find out for yourself.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (37, '1:42', 'Will.I.Am & Brittney Spears');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (38, 820, 'Santeria', 'New era', '', 'https://img.youtube.com/vi/AEYN5w4T_aM/0.jpg', 'Moving over to a slower pace, written by the hit 1990s rock band Sublime, we have Santeria at #8 for the playlist. Originally formed in Long Beach California, Sublime is a rock band that also dabbled in performing reggae and pop, hence their song “Santeria.” “Santeria” was one of their last songs released, which was in 1996. After that, the band broke up following the tragic death of one of its members. Other prominent songs to listen to by Sublime include “Smoke Two Joints,” “5446/Ball and Chain,” “Pawn Shop,” “40oz to Freedom,” and “Summertime.”');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (38, '2:47', 'Sublime');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (39, 742, 'Alright', 'Classical', '', 'https://img.youtube.com/vi/Z-48u_uWMHY/0.jpg', 'Changing genres once again, we start with our first rap song on this playlist. In 2015, Grammy award-winning artist Kendrick Lamar came out with his song “Alright” from his album To Pimp a Butterfly. Lamar’s song “Alright” peaked on the charts at #14 and lasted for 17 weeks there. Whether you like listening to Pop Smoke, Ski Mask the Slump God, or Drake, Kendrick Lamar should be at the top of your list, especially with this banger.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (39, '2:59', 'Kendrick Lamar');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (40, 1250, 'Thrift Shop', 'New era', '', 'https://img.youtube.com/vi/QK8mJJJvaes/0.jpg', 'Sliding in with another rap song, this time from 2012, we have “Thrift Shop” by Macklemore and Ryan Lewis. From their album The Heist, “Thrift Shop” became a sensation not only within the United States but within over twenty countries as well. Thrift shop even was the #1 spot on 4 US billboards. Macklemore received a Grammy award in 2014 for Best Rap Performance and Best Rap Song. If you have got five minutes to spare, check out their music video on YouTube!');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (40, '1:18', 'Macklemore & Ryan Lewis');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (41, 993, 'Blurred Lines', 'Jazz', '', 'https://img.youtube.com/vi/yyDUC1LUXSU/0.jpg', 'Moving forward one year into 2013, we have “Blurred Lines” by Robin Thicke and Pharrell Williams. This suggestive song centered around “getting lucky,” (not to be confused with Daft Punk’s song “Get Lucky”) was released in 2013 and had some initial backlash from the populace for being misogynistic. There was even a lawsuit regarding this song due to the singers’ “noticeably ripping off Marvin Gaye’s “Got to Give it Up.” Despite all of the bad press this song received, it still hit the #1 position on the billboards and stayed on the billboards for 51 weeks.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (41, '1:50', 'Robin Thicke & Pharrell Williams');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (42, 478, 'Stairway to Heaven', 'Jazz', '', 'https://img.youtube.com/vi/QkF3oxziUI4/0.jpg', 'Commonly known as the forbidden riff in guitar stores, “Stairway to Heaven” is one of the most known songs in the entire world. A little just over 8 minutes of guitars, drums, and singing, Stairway to Heaven has been debated by multiple people what its true meaning actually is. And this is the true beauty of art when there are multiple meanings to the same lyrics everyone has heard before. Another huge hit for Led Zeppelin, Stairway surprisingly never hit the charts, yet is one of the most iconic songs to date.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (42, '2:21', 'Led Zeppelin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (43, 1159, 'Iron Man', 'Classical', '', 'https://img.youtube.com/vi/F01UTYg79KY/0.jpg', 'Not to be confused with Marvel’s character Iron Man played by Robert Downy Jr., this Iron Man comes from another huge rock band that started in 1968 and is still going strong. Black Sabbath released “Iron Man” in 1970, a whopping amount of years in the distance! Among the original members of Black Sabbath were Ozzy Osbourne (singer), Tony Lommi (guitarist), Geezer Butler (bassist), and Bill Ward (drummer). Over the course of many years though, the band cycled through 21 more people, replacing each other. Ozzy Osbourne was fired from the band in 1979. It would not be until 1998 that Osbourne would reunite with his fellow original members of the band. Iron Man at its peak time placed in #52 and was on the charts for 10 weeks. Today, it is one of the most known songs of Black Sabbath, along with “War Pigs” and “Paranoid.”');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (43, '2:55', 'Black Sabbath');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (44, 613, 'September', 'Classical', '', 'https://img.youtube.com/vi/Gs069dndIYk/0.jpg', 'Played in several movies throughout the 2000s and more disco clubs than anyone can count, “September” by Earth, Wind, and Fire were some of the hottest songs throughout the disco era. Released in 1978, “September” hit the #1 spot on the US Hot R&B/Hip Hop Songs Billboard. With over 530 million views on YouTube, this song is now most celebrated in, you guessed it, the month of September. Specifically, on the 21st night of the month.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (44, '1:36', 'Earth, Wind, & Fire');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (45, 1109, 'Come As You Are', 'Jazz', '', 'https://img.youtube.com/vi/vabnZ9-ex7o/0.jpg', 'Back with another Kurt Cobain song, “Come As You Are” basically tells the audience that even if you are messed up and confused, you are still welcomed. Some argue the song is about substances, and others argue it is about what people are expected to act like. Overall though, the meaning is up to the person listening. From the album Nevermind (which was almost called Sheep), Cobain wooed audiences with his song, making the album become platinum by selling millions of copies. Nevermind’s album picture is one of the most-known album covers in music history with a naked baby underwater fishing for a dollar bill. The other famous song from Nevermind is “Smells Like Teen Spirit”, which was previously mentioned on this list.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (45, '2:0', 'Nirvana');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (46, 1308, 'Welcome to The Jungle', 'Jazz', '', 'https://img.youtube.com/vi/o1tj2zJ2Wvg/0.jpg', 'Another hit Guns N’ Roses song, “Welcome to The Jungle” comes from the same album as #6 “Sweet Child O’Mine.” In the 2017 movie Jumanji: Welcome to the Jungle, the producers decided to add Guns N’ Roses #7 hit song on the charts. After all, this song is the movie’s namesake.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (46, '1:43', 'Guns N’Roses');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (47, 1926, 'Mirrors', 'Classical', '', 'https://img.youtube.com/vi/uuZE_IRwLNI/0.jpg', 'If you are a Justin Timberlake fan, you’ll love the next song on this playlist. Justin Timberlake’s 2013 “Mirrors” is a love song that shows that your significant other, whoever they may be, ends up being your other half. That the person who you did not know for a long time has now become so important in your life that you are not complete without them. “Mirrors” is without a doubt a good song to get you in your feels. If you are having one of those nights, or even if you are madly in love with someone and want to relate to them how much they mean to you, this is the song for that.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (47, '1:57', 'Justin Timberlake');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (48, 853, 'Let’s Groove', 'Jazz', '', 'https://img.youtube.com/vi/Lrle0x_DHBM/0.jpg', 'Back into the disco era, another hit by the beloved Earth, Wind, and Fire, is #18 “Let’s Groove.” Now a famous audio clip on social media platforms, everyone is partaking in the “spice of life” that the band sings about. Released in 1981, “Let’s Groove” peaked at #3 on the charts and stayed on the charts for 24 weeks. Let’s Groove also managed to take the #1 spot on the US Billboard Hot Soul Singles. In spite of all the backlash that was happening to the disco industry, Earth, Wind, and Fire still managed to create a hit piece that is still listened to today. Now, it has been put onto social media and has millions of new listeners.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (48, '1:26', 'Earth, Wind, & Fire');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (49, 803, 'Despacito', 'New era', '', 'https://img.youtube.com/vi/kJQP7kiw5Fk/0.jpg', 'Coming on as our first foreign language song, “Despacito,” meaning “slowly” in Spanish, became a huge hit among younger generations. Luis Fonsi and Daddy Yankee originally sang this song when it came out in 2017, and a later version came out with Justin Bieber singing along, creating an English-Spanish version of the song. “Despacito” is all about desiring a relationship with someone but in a romantic way. Both the Spanish and English versions can be found on YouTube and are fun to dance to.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (49, '2:25', 'Luis Fonsi & Daddy Yankee');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (50, 1944, 'Kashmir', 'Classical', '', 'https://img.youtube.com/vi/tzVJPgCn-Z8/0.jpg', 'Moving on back to 1970s rock, we have another hit from Led Zeppelin, which, like “Stairway to Heaven,” is also around 8 minutes long. Not to be confused with the rock band Kashmir, the song “Kashmir” has been known not only to be replayed by many cover bands but even high school orchestras. Although at first, the lyrics might seem a bit overwhelming, once they are broken down, you learn that the song is about a journey through the roads of Southern Morocco. The next time you listen to “Kashmir,” try to imagine yourself driving along a sandy long stretch of road with desert on either side.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (50, '2:20', 'Led Zeppelin');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (51, 1561, 'War Pigs', 'New era', '', 'https://img.youtube.com/vi/bc5Nk1DXyEY/0.jpg', 'Moving back to Black Sabbath but still staying in the 1970s, “War Pigs” is the ultimate anti-establishment song meant for everyone. Released in 1970 in protest to the Vietnam War raging on, “War Pigs” addressed the problem with society. That being that the rich have the poor fight their battles and the ones who start the wars never fight in them, but instead send young men in their stead to die, and for what? “War Pigs” was one of the songs that made Black Sabbath so famous because they were able to get the anti-war activists and some of the counterculture people on their side, which gave them rising fame and popularity.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (51, '1:15', 'Black Sabbath');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (52, 1563, 'Shake Your Groove Thing', 'Classical', '', 'https://img.youtube.com/vi/e-LeujZNV08/0.jpg', 'If you are looking to hype your night up and release some endorphins, you should listen to “Shake Your Groove Thing.” Recorded and released in 1978, Peaches and Herb show people how to shake their groove thing (their rear ends). Peaches and Herb’s “Shake Your Groove Thing” at its height reached the #5 spot on the U.S. Hot 100 Billboard. The same people that wrote #4, “I Will Survive,” which was Freddie Perren and Dino Fekaris also wrote this popular disco song.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (52, '2:21', 'Peaches and Herb');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (53, 636, 'Jailhouse Rock', 'Jazz', '', 'https://img.youtube.com/vi/PpsUOOfb-vE/0.jpg', 'From the 1957 film Jailhouse Rock also comes to the classic song “Jailhouse Rock”. In both the movie and the song, Elvis Presley absolutely crushes his performance. Known as the “King of Rock and Roll”, how can we go down this playlist without mentioning the essential listen piece from the talented Elvis Presley. Even though Elvis Presley died in 1977, his music still lives on today.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (53, '1:9', 'Elvis Presley');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (54, 1908, 'Hey Jude', 'New era', '', 'https://img.youtube.com/vi/A_MjCqQoLLA/0.jpg', 'Likewise with the Late Elvis Presley, one cannot possibly go through a list of the best songs ever and not mention something from one of the most famous bands of all time, The Beatles. The Beatles formed in Liverpool, England in 1957. It was only until 1960 they cemented their name into history which we all know them as today. Even though The Beatles were only active for 10 years until 1970, they made massive shockwaves throughout the world with their songs, including “Hey Jude.” “Hey Jude” earned the #1 spot in 18 countries and the #1 spot on 3 different US billboards. Like many of the most iconic Beatles songs, “Hey Jude” was and still is a sensational hit.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (54, '1:33', 'The Beatles');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (55, 734, 'New York, New York', 'Jazz', '', 'https://img.youtube.com/vi/le1QF3uoQNg/0.jpg', 'Originally recorded by Liza Minelli in 1977 for the movie New York, New York, Frank Sinatra recorded a cover of the song in 1979 and now is most notable for the person who sings this song. Among the most well-known of singers from the 1900s, Frank Sinatra has had his songs and covers in many movies throughout the decades. This is one of the most well-known songs about New York of all time!');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (55, '1:1', 'Frank Sinatra');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (56, 1086, 'I Shot the Sheriff', 'Jazz', '', 'https://img.youtube.com/vi/sG52YAe8Crg/0.jpg', 'A common phrase that used to be used, “I shot the sheriff, but I did not shoot the deputy,” Bob Marley’s 1973 song “I Shot the Sheriff” is a combination of rock, reggae, soft rock, and pop all in one. Throughout the years there have been many covers of this song, but none other so famous than the Eric Clapton version. Bob Marley is a legend in the reggae world and is considered the king of reggae. “I Shot the Sheriff” hit the #1 spot on the US Billboard Hot 100 as well as many other countries.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (56, '2:20', 'Bob Marley');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (57, 926, 'Chop Suey', 'Classical', '', 'https://img.youtube.com/vi/CSvFpBOe8eY/0.jpg', 'This list is full of all types of genres, from rap to reggae, pop to rock. One genre that has not been mentioned yet though is metal/heavy metal. That is until now. Up next on our list is “Chop Suey” by System of a Down. System of a Down has been active from the years of 1994-2006 and 2010 to the present. Some of System of a Down’s other prominent songs include “B.Y.O.B.,” “Ariels,” “Toxicity,” and “Spiders.” “Chop Suey” now has over 1 billion views on YouTube and is headed by lead singer Serj Tankian. The other members of the band include Daron Malakian (guitarist), Shavo Odadjian (bassist), and John Dolmayan (drummer).');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (57, '2:45', 'System of a Down');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (58, 713, 'American Pie', 'Jazz', '', 'https://img.youtube.com/vi/iX_TFkut1PM/0.jpg', 'The last 8-minute song in the queue of best songs of all time, “American Pie” is up next on the list. “American Pie” came out in 1971 by Don McLean. “American Pie,” tells the story of the tragic deaths of Buddy Holly, J.P. Richardson (The Big Bopper), and Ritchie Valens. As McLean mentions many times in the song, it was “the day the music died.” A somewhat somber song in its meaning, the song has an upbeat and catchy tune to sing along to.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (58, '1:7', 'Don McLean');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (59, 1501, 'Buffalo Soldier', 'Jazz', '', 'https://img.youtube.com/vi/QiESgCu9Ehw/0.jpg', 'Another hit by “King of Reggae” Bob Marley, is the song “Buffalo Soldier.” “Buffalo Soldier” is a term given to African Americans by Native Americans, who thought their hair and dreadlocks felt like that of a buffalo’s pelt. Although the late king of reggae is no longer with us, no matter what song he sang, he always kept the same chill vibe throughout.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (59, '1:10', 'Bob Marley');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (60, 629, 'Come Together', 'New era', '', 'https://img.youtube.com/vi/45cYwDMibGo/0.jpg', 'Back to the table is The Beatles. This time, with their song, “Come Together.” “Come Together” was released in 1969 as a single on the album Abbey Road. Similar to #11 “Blurred Lines,” there was a lawsuit regarding “Come Together” because it sounded too similar to Chuck Berry’s “You Can’t Catch Me.”');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (60, '2:55', 'The Beatles');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (61, 259, 'Bohemian Rhapsody', 'Classical', '', 'https://img.youtube.com/vi/fJ9rUzIMcZQ/0.jpg', 'If you would like to know what existentialism sounds like, look no further. The late Freddie Mercury (1946-1991) wrote “Bohemian Rhapsody” for Queen’s album A Night at the Opera in 1975. Bohemian Rhapsody was able to sell more than a million copies, making it Queen’s most famous song. The song is split up into 6 sections, consisting of the intro, ballad, guitar solo, opera, hard rock, and outro.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (61, '2:19', 'Queen');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (62, 1920, 'Smooth Criminal', 'Classical', '', 'https://img.youtube.com/vi/h_D3VFfhvs4/0.jpg', 'From the movie This Is It, the king of pop strikes again on this list with his absolute banger “Smooth Criminal.” Not only is this song famous for its catchy tune and words, but for its dancing, choreographed by Jeffery Daniel. The move that catches people off guard and that always amazes people is Michael Jackson’s leaning trick where he stands on the floor and leans more than 45 degrees. For scale, the normal human body cannot usually lean more than 30-35 degrees without a considerable amount of training.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (62, '2:34', 'Michael Jackson');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (63, 252, 'Ring of Fire', 'Classical', '', 'https://img.youtube.com/vi/1WaV2x8GXj0/0.jpg', 'Changing genres again, this list has not hit on a country song. All the way back in 1967, Johnny Cash released his song “Ring of Fire” in his album Greatest Hits, Vol. 1. Even though “Ring of Fire” only peaked at #45 on the US Hot Country Songs, Johnny Cash is a staple of country music in America, and “Ring of Fire” is short, relatable, and all-around fun to jam out to.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (63, '2:34', 'Johnny Cash');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (64, 1740, 'Latch', 'Jazz', '', 'https://img.youtube.com/vi/k0jLE7tTwjY/0.jpg', 'Jumping forward about 50 years, a more modern piece of music that is among the best of all time is “Latch.” Here, Disclosure and Sam Smith in their album Settle sing “Latch,” which is a love song focused on truly loving someone to the point of never wanting to let go of that person.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (64, '1:16', 'Disclosure & Sam Smith');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (65, 1856, 'Bad and Boujee', 'Classical', '', 'https://img.youtube.com/vi/S-sJp1FfG7Q/0.jpg', 'Moving on to another rap song that most people have probably heard before is none other than Migos’ “Bad and Boujee.” “Bad and Boujee” features Lil Uzi Vert, most notable nowadays for putting a 24 million dollar diamond on his forehead to wear as jewelry. If you are a fan of rap or Migos, this song is a must on any playlist.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (65, '2:18', 'Migos & Lil Uzi Vert');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (66, 1509, 'Lean on Me', 'Classical', '', 'https://img.youtube.com/vi/fOZ-MySzAac/0.jpg', 'Shifting to a different genre and slower pace of the song, “Lean on Me” is the perfect feel-good song to get the emotions going and want to help others out in your life. Bill Withers wrote and released Lean on Me in 1972, and won a Grammy for Best R&B Song. Recently deceased (1938-2020), Bill Withers lives on in his songs, especially this one.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (66, '1:22', 'Bill Withers');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (67, 258, 'Dream On', 'Jazz', '', 'https://img.youtube.com/vi/89dGC8de0CA/0.jpg', 'Aerosmith released “Dream On” in 1973 and it has become known for its iconic loud scream near the end. Dream On is sung by the vocalist Steven Tyler, who also plays the piano. Other members of the original band include Joe Perry (lead guitarist), Brad Whitford (guitarist), Tom Hamilton (bassist), and Joey Kramer (drummer). Other songs by Aeormsith include Livin’ On The Edge, Cryin’, Crazy, and What It Takes.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (67, '1:21', 'Aerosmith');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (68, 961, 'Paint It, Black', 'New era', '', 'https://img.youtube.com/vi/EBUFtoC2oj4/0.jpg', 'An oldie but a goodie, this 1966 hit became a sensation among most generations alive today and without a doubt belongs on this list. The Rolling stones wrote and released “Paint It Black” in 1966 in their album Aftermath. Over the years, “Paint It Black” became associated as a song relating to the Vietnam War. Since “Paint It Black” was played at the end credits of the 1987 movie Full Metal Jacket, which was about the Vietnam War, this made the song guilty by association one may say.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (68, '2:23', 'The Rolling Stones');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (69, 1104, 'Hotel California', 'Jazz', '', 'https://img.youtube.com/vi/BciS5krYL80/0.jpg', 'A classic song if ever there were any is “Hotel California.” In 1976, the Eagles released “Hotel California” from their album Hotel California. They ended up winning a Grammy award for Record of the Year. Supposedly, “Hotel California” is about a first-hand experience at a mental hospital. Some argue it is about substance addiction, and others argue it is about the world below. I will leave that meaning up to you though based on what you hear.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (69, '1:17', 'The Eagles');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (70, 467, 'Somebody That I Used To Know', 'New era', '', 'https://img.youtube.com/vi/8UVNT4wvIGY/0.jpg', '“Somebody That I Used To Know” is one of the best-known one-hit wonders of the Gen Z generation. Released in 2011, Gotye sang the iconic song that became a sensation across the U.S. and over twenty countries. In the U.S. alone, it hit the #1 spot for 10 separate billboards! Gotye is a Belgian-Australian musician born in 1980. His full name is Wouter De Backer.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (70, '1:4', 'Gotye');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (71, 1632, 'Somewhere Over the Rainbow', 'New era', '', 'https://img.youtube.com/vi/V1bFr2SWP1I/0.jpg', '“Somewhere Over the Rainbow” is one of those feel-good songs you put on when you are just enjoying life or want to rally up your spirits. “Somewhere Over the Rainbow” was sung by the late Israel Kamakawiwo’ole (1959-1997). Unfortunately, Kamakawiwo’ole passed away due to respiratory failure at the age of 38, but he lives on through his ukulele-played song.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (71, '2:45', 'Israel Kamakawiwo’ole');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (72, 752, 'Fortunate Son', 'Jazz', '', 'https://img.youtube.com/vi/ec0XKhAHR5I/0.jpg', 'Another solid gold oldie and one of the most famous songs in existence is “Fortunate Son.” “Fortunate Son” is a 1969 rock song written by Creedence Clearwater Revival and is most notorious for being associated with the Vietnam War. The song is a protest song that tells the story of rich people starting wars but never having to experience the horrors of war, so much so that even their children are guarded against it. However, the rich will make the poor fight their wars. It has the same theme as “War Pigs,” but is sung a bit more upbeat.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (72, '2:32', 'Creedence Clearwater Revival');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (73, 241, 'Let Her Go', 'Classical', '', 'https://img.youtube.com/vi/RBumgq5yVrA/0.jpg', 'Transitioning into a more somber song is #43 “Let Her Go.” In 2012, Passenger wrote “Let Her Go” in his Album All the Little Lights. “Let Her Go’s” meaning is exactly what it sounds like. If you are not in a good spot with your significant other and constantly fight then you will let them go because you two are not good for each other. It is only after you let them go that you realize you loved them. It happens to the best of us.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (73, '1:51', 'Passenger');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (74, 345, 'Take Me Home, Country Roads', 'Classical', '', 'https://img.youtube.com/vi/1vrEljMfXYo/0.jpg', 'A signature song is still sung today, Artist John Denver wrote “Take Me Home, Country Roads” all the way back in 1970. This song has been bringing joy to millions over the past so many decades. The best part about this song is that it is based on the real geography of roads that lead into West Virginia. The road is known as Clopper Road which leads into West Virginia from Maryland.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (74, '1:34', 'John Denver');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (75, 646, 'What A Wonderful World', 'Jazz', '', 'https://img.youtube.com/vi/VqhCQZaH4Vs/0.jpg', 'If you’ve ever watched the original Toy Story Movie, then you have most likely heard Louis Armstrong’s “What a Wonderful World.” Louis Armstrong always had a positive outlook on life, and this song is exactly about that. There is nothing but positive vibes that come from this song and we all need happiness in our lives, so if you’re feeling a bit down, I encourage you to listen to this.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (75, '2:26', 'Louis Armstrong');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (76, 856, 'Africa', 'Jazz', '', 'https://img.youtube.com/vi/FTQbiNvZqaY/0.jpg', 'Most notably a meme song as of 2018, Toto’s “Africa” was already a popular song before its revival back in the late 2010s. “Africa” originally came out in 1982 and hit the #1 spot on the US Billboard Hot 200. Toto ended up selling over 6 million albums in the US alone and millions more worldwide.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (76, '1:45', 'Toto');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (77, 1235, 'Beat It', 'Classical', '', 'https://img.youtube.com/vi/oRdxUFDoQe0/0.jpg', 'Our final king of pop songs for this playlist, Michael Jackson kills it again with his 1982 hit “Beat It.” On the same album as “P.Y.T.,” “Billie Jean,” and “Thriller,” “Beat It” is a song that tells you to basically be the bigger person and avoid fights as much as you can. A key strategy from Sun Tzu’s Art of War, Jackson sings us the same principle of the best fight is no fight.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (77, '1:11', 'Michael Jackson');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (78, 222, 'Thunder', 'New era', '', 'https://img.youtube.com/vi/fKopy74weus/0.jpg', 'Coming in with a more modern song as we draw near the end of our list is #48 “Thunder.” One of the biggest bands of today, Imagine Dragons released “Thunder” in 2017 and it did not take long for the song to hit not 1, but 3 US billboards. This song is all about coming over all of the challenges in your life and being able to achieve the lifelong goals you have set for yourself. In order to reap the rewards of life, one must face great trial and tribulation, hence the lightning and thunder that is constantly referred to.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (78, '1:28', 'Imagine Dragons');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (79, 1513, 'Can’t Help Falling In Love', 'Classical', '', 'https://img.youtube.com/vi/vGJTaP6anOU/0.jpg', '“Can’t Help Falling in Love” is a song that has been played countless times at weddings, I can assure you that. In his 1961 song, Elvis Presley sang this little tune that conveys all of the love someone might have for someone as if they were in a perpetual honeymoon phase. This song has become so popular, it has had cover after cover done on it. One of the most famous covers is by Pentatonix.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (79, '2:45', 'Elvis Presley');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (80, 257, 'Piano Man', 'Jazz', '', 'https://img.youtube.com/vi/gxEPV4kolz0/0.jpg', 'Another infamous wedding song that we can’t get out of my head anymore: up next is Billy Joel’s, “Piano Man.” Billy Joel released “Piano Man” all the way back in 1973 and it is still going strong as ever. At its peak, “Piano Man” hit the #1 spot on the US Billboard Hot 100. In the current years, there is a joke going around about “Piano Man,” which states something along the lines of “for a song that’s called Piano Man the guy with the harmonica seems to never shut up.” Still though, nothing can truly deteriorate the epic nature of this classic hit.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (80, '2:8', 'Billy Joel');

INSERT INTO WOLF.PRODUCT (ID, PRICE, NAME, GENRE, RELEASE, IMAGEURL, DESCRIPTION) VALUES (81, 1374, 'Careless Whisper', 'Classical', '', 'https://img.youtube.com/vi/izGwDsrQ1eQ/0.jpg', 'Last, but certainly not least by a long shot, we have on our list of best songs of all time George Michael’s “Careless Whisper.” “Careless Whisper” was able to snatch the #1 spot on the US Billboards and stayed on for 22 weeks in 1985. Sadly, like many of the great artists in this lineup, George Micheals died on Christmas day in 2016 in Goring, United Kingdom. He passed away due to heart and liver disease at the age of 53.');
INSERT INTO WOLF.SONG (ID, LENGTH, PRODUCER) VALUES (81, '2:47', 'George Michael');

