INSERT INTO WOLF.STORAGE (ID, NAME, CAPACITY, CITY)
VALUES (1, 'Szeged Ujszeged', 4000, 'Szeged');

INSERT INTO WOLF.STORAGE (ID, NAME, CAPACITY, CITY)
VALUES (2, 'Szeged Centrum', 300, 'Szeged');

INSERT INTO WOLF.STORAGE (ID, NAME, CAPACITY, CITY)
VALUES (3, 'Budapest 1.', 20000, 'Budapest');

INSERT INTO WOLF.STORAGE (ID, NAME, CAPACITY, CITY)
VALUES (4, 'Budapest 2.', 13000, 'Budapest');

