-- PRODUCT --
CREATE TABLE "WOLF"."PRODUCT"
(	"ID" NUMBER(20,0) NOT NULL ENABLE,
     "PRICE" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE,
     "NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "GENRE" VARCHAR2(100 BYTE),
     "RELEASE" VARCHAR2(100 BYTE),
     "IMAGEURL" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "LANGUAGE" VARCHAR2(300 BYTE),
     "DESCRIPTION" VARCHAR2(2000 BYTE),
     "LONGNAME" VARCHAR2(20 BYTE),
     "QUANTITY" NUMBER(20,0) DEFAULT 1 NOT NULL ENABLE,
     CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;


-- BOOK ---
CREATE TABLE "WOLF"."BOOK"
(	"ID" NUMBER NOT NULL ENABLE,
     "PAGENUMBER" NUMBER(20,0),
     "TYPE" VARCHAR2(100 BYTE),
     "AUTHOR" VARCHAR2(100 BYTE),
     CONSTRAINT "BOOK_ID_FK" FOREIGN KEY ("ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;


-- FILM ---
CREATE TABLE "WOLF"."FLIM"
(	"ID" NUMBER NOT NULL ENABLE,
     "DIRECTOR" VARCHAR2(500 BYTE),
     "LENGTH" NUMBER,
     CONSTRAINT "FLIM_FK1" FOREIGN KEY ("ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;


-- SONG ---
CREATE TABLE "WOLF"."SONG"
(	"ID" NUMBER NOT NULL ENABLE,
     "LENGTH" VARCHAR2(400 BYTE),
     "PRODUCER" VARCHAR2(400 BYTE),
     CONSTRAINT "SONG_FK1" FOREIGN KEY ("ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;



-- CLIENT ---
CREATE TABLE "WOLF"."CLIENT"
(	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "EMAIL" VARCHAR2(22 BYTE) NOT NULL ENABLE,
     "PPASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "FIRSTNAME" VARCHAR2(20 BYTE),
     "LASTNAME" VARCHAR2(20 BYTE),
     "AVATAR" VARCHAR2(20 BYTE),
     "ADDRESS_ID" NUMBER,
     "IS_ADMIN" NUMBER(1,0) DEFAULT 0,
     "ISMEMBER" NUMBER(1,0) DEFAULT 0,
     CONSTRAINT "CLIENT_PK" PRIMARY KEY ("USERNAME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE,
     CONSTRAINT "C_ADDRESS_ID_FK" FOREIGN KEY ("ADDRESS_ID")
         REFERENCES "WOLF"."ADDRESS" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;



-- PURCHASE ---
CREATE TABLE "WOLF"."PURCHASE"
(	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
     "PRODUCTID" NUMBER NOT NULL ENABLE,
     "PDATE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
     "QUANTITY" NUMBER NOT NULL ENABLE,
     CONSTRAINT "PURCHASE_FK1" FOREIGN KEY ("PRODUCTID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;


-- WISHLIST --
CREATE TABLE "WOLF"."WISHLIST"
(	"USERNAME" VARCHAR2(300 BYTE) NOT NULL ENABLE,
     "PRODUCT_ID" NUMBER NOT NULL ENABLE,
     CONSTRAINT "WISHLIST_USERNAME_FK" FOREIGN KEY ("USERNAME")
         REFERENCES "WOLF"."CLIENT" ("USERNAME") ENABLE,
     CONSTRAINT "WISHLIST_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;


-- STORAGE --
CREATE TABLE "WOLF"."STORAGE"
(	"ID" NUMBER NOT NULL ENABLE,
     "NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE,
     "CAPACITY" NUMBER NOT NULL ENABLE,
     "CITY" VARCHAR2(300 BYTE) NOT NULL ENABLE,
     CONSTRAINT "STORAGE_PK" PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;
CREATE OR REPLACE EDITIONABLE TRIGGER "WOLF"."STORAGE__ID_TRG"
    BEFORE INSERT ON STORAGE
    FOR EACH ROW
BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
        IF INSERTING AND :NEW.ID IS NULL THEN
            SELECT STORAGE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
        END IF;
    END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WOLF"."STORAGE__ID_TRG" ENABLE;


-- STORED_PRODUCTS --
CREATE TABLE "WOLF"."STORED_PRODUCTS"
(	"STORAGE_ID" NUMBER NOT NULL ENABLE,
     "PRODUCT_ID" NUMBER NOT NULL ENABLE,
     "QUANTITY" NUMBER DEFAULT 0,
     CONSTRAINT "SP_PRODUCT_ID_FK" FOREIGN KEY ("STORAGE_ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE,
     CONSTRAINT "SP_STORAGE_ID_FK" FOREIGN KEY ("STORAGE_ID")
         REFERENCES "WOLF"."STORAGE" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;


-- ADDRESS --
CREATE TABLE "WOLF"."ADDRESS"
(	"ID" NUMBER NOT NULL ENABLE,
     "CITY" VARCHAR2(300 BYTE) NOT NULL ENABLE,
     "ZIPCODE" NUMBER NOT NULL ENABLE,
     "STREET" VARCHAR2(300 BYTE) NOT NULL ENABLE,
     "HOUSE_NUMBER" NUMBER NOT NULL ENABLE,
     CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "WOLF"."ADDRESS_ID_TRG"
    BEFORE INSERT ON ADDRESS
    FOR EACH ROW
BEGIN
    <<COLUMN_SEQUENCES>>
    BEGIN
        IF INSERTING AND :NEW.ID IS NULL THEN
            SELECT ADDRESS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
        END IF;
    END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WOLF"."ADDRESS_ID_TRG" ENABLE;
