--  PRODUCT --
CREATE TABLE "WOLF"."PRODUCT"
(
    "ID"       NUMBER(20,0) NOT NULL ENABLE,
    "PRICE"    NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE,
    "NAME"     VARCHAR2(100 BYTE) NOT NULL ENABLE,
    "GENRE"    VARCHAR2(100 BYTE),
    "RELEASE"  VARCHAR2(100 BYTE),
    "IMAGEURL" VARCHAR2(100 BYTE) NOT NULL ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";


--  BOOK ---

CREATE TABLE "WOLF"."BOOK"
(
    "ID"         NUMBER NOT NULL ENABLE,
    "PAGENUMBER" NUMBER(20,0),
    "TYPE"       VARCHAR2(100 BYTE),
    "AUTHOR"     VARCHAR2(100 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";



--  FILM ---


--  SONG ---


-- CLIENT ---

CREATE TABLE "WOLF"."CLIENT"
(	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "EMAIL" VARCHAR2(22 BYTE) NOT NULL ENABLE,
     "PPASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "FIRSTNAME" VARCHAR2(20 BYTE),
     "LASTNAME" VARCHAR2(20 BYTE),
     "AVATAR" VARCHAR2(20 BYTE),
     CONSTRAINT "CLIENT_PK" PRIMARY KEY ("USERNAME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

