-- PRODUCT --
CREATE TABLE "WOLF"."PRODUCT"
(	"ID" NUMBER(20,0) NOT NULL ENABLE,
     "PRICE" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE,
     "NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "GENRE" VARCHAR2(100 BYTE),
     "RELEASE" VARCHAR2(100 BYTE),
     "IMAGEURL" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "LANGUAGE" VARCHAR2(300 BYTE),
     "DESCRIPTION" VARCHAR2(2000 BYTE),
     "LONGNAME" VARCHAR2(20 BYTE),
     CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

-- BOOK ---
CREATE TABLE "WOLF"."BOOK"
(	"ID" NUMBER NOT NULL ENABLE,
     "PAGENUMBER" NUMBER(20,0),
     "TYPE" VARCHAR2(100 BYTE),
     "AUTHOR" VARCHAR2(100 BYTE),
     CONSTRAINT "BOOK_ID_FK" FOREIGN KEY ("ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

-- FILM ---
CREATE TABLE "WOLF"."FLIM"
(	"ID" NUMBER NOT NULL ENABLE,
     "DIRECTOR" VARCHAR2(500 BYTE),
     "LENGTH" NUMBER,
     CONSTRAINT "FLIM_FK1" FOREIGN KEY ("ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

-- SONG ---
CREATE TABLE "WOLF"."SONG"
(	"ID" NUMBER NOT NULL ENABLE,
     "LENGTH" NUMBER,
     "PRODUCER" VARCHAR2(400 BYTE),
     CONSTRAINT "SONG_FK1" FOREIGN KEY ("ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

-- CLIENT ---
CREATE TABLE "WOLF"."CLIENT"
(	"USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "EMAIL" VARCHAR2(22 BYTE) NOT NULL ENABLE,
     "PPASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "FIRSTNAME" VARCHAR2(20 BYTE),
     "LASTNAME" VARCHAR2(20 BYTE),
     "AVATAR" VARCHAR2(20 BYTE),
     CONSTRAINT "CLIENT_PK" PRIMARY KEY ("USERNAME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

-- PURCHASE ---
CREATE TABLE "WOLF"."PURCHASE"
(	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
     "PRODUCTID" NUMBER NOT NULL ENABLE,
     "PDATE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
     "QUANTITY" NUMBER NOT NULL ENABLE,
     CONSTRAINT "PURCHASE_FK1" FOREIGN KEY ("PRODUCTID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;

-- WISHLIST --
CREATE TABLE "WOLF"."WISHLIST"
(	"USERNAME" VARCHAR2(300 BYTE) NOT NULL ENABLE,
     "PRODUCT_ID" NUMBER NOT NULL ENABLE,
     CONSTRAINT "WISHLIST_USERNAME_FK" FOREIGN KEY ("USERNAME")
         REFERENCES "WOLF"."CLIENT" ("USERNAME") ENABLE,
     CONSTRAINT "WISHLIST_PRODUCT_ID_FK" FOREIGN KEY ("PRODUCT_ID")
         REFERENCES "WOLF"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;
