-- USER WOLF ---

-- USER SQL
CREATE USER "WOLF" IDENTIFIED BY "yolo"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "WOLF" ;
GRANT "DV_MONITOR" TO "WOLF" ;
GRANT "CTXAPP" TO "WOLF" ;
GRANT "DV_AUDIT_CLEANUP" TO "WOLF" ;
GRANT "SPATIAL_CSW_ADMIN" TO "WOLF" ;
GRANT "APEX_GRANTS_FOR_NEW_USERS_ROLE" TO "WOLF" ;
GRANT "WFS_USR_ROLE" TO "WOLF" ;
GRANT "EM_EXPRESS_ALL" TO "WOLF" ;
GRANT "WM_ADMIN_ROLE" TO "WOLF" ;
GRANT "OLAP_USER" TO "WOLF" ;
GRANT "OLAP_XS_ADMIN" TO "WOLF" ;
GRANT "DV_SECANALYST" TO "WOLF" ;
GRANT "CSW_USR_ROLE" TO "WOLF" ;
GRANT "XS_CACHE_ADMIN" TO "WOLF" ;
GRANT "GDS_CATALOG_SELECT" TO "WOLF" ;
GRANT "SCHEDULER_ADMIN" TO "WOLF" ;
GRANT "PROVISIONER" TO "WOLF" ;
GRANT "AUDIT_ADMIN" TO "WOLF" ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "WOLF" ;
GRANT "DV_REALM_RESOURCE" TO "WOLF" ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "WOLF" ;
GRANT "DELETE_CATALOG_ROLE" TO "WOLF" ;
GRANT "XDB_WEBSERVICES" TO "WOLF" ;
GRANT "DV_PUBLIC" TO "WOLF" ;
GRANT "LBAC_DBA" TO "WOLF" ;
GRANT "OPTIMIZER_PROCESSING_RATE" TO "WOLF" ;
GRANT "RECOVERY_CATALOG_USER" TO "WOLF" ;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "WOLF" ;
GRANT "GSMUSER_ROLE" TO "WOLF" ;
GRANT "GATHER_SYSTEM_STATISTICS" TO "WOLF" ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "WOLF" ;
GRANT "GSM_POOLADMIN_ROLE" TO "WOLF" ;
GRANT "DV_ADMIN" TO "WOLF" ;
GRANT "HS_ADMIN_ROLE" TO "WOLF" ;
GRANT "XS_SESSION_ADMIN" TO "WOLF" ;
GRANT "DV_GOLDENGATE_ADMIN" TO "WOLF" ;
GRANT "IMP_FULL_DATABASE" TO "WOLF" ;
GRANT "DV_XSTREAM_ADMIN" TO "WOLF" ;
GRANT "DV_PATCH_ADMIN" TO "WOLF" ;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "WOLF" ;
GRANT "EJBCLIENT" TO "WOLF" ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "WOLF" ;
GRANT "JMXSERVER" TO "WOLF" ;
GRANT "OLAP_DBA" TO "WOLF" ;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "WOLF" ;
GRANT "JAVAIDPRIV" TO "WOLF" ;
GRANT "SELECT_CATALOG_ROLE" TO "WOLF" ;
GRANT "JAVADEBUGPRIV" TO "WOLF" ;
GRANT "CONNECT" TO "WOLF" ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "WOLF" ;
GRANT "OEM_MONITOR" TO "WOLF" ;
GRANT "APEX_ADMINISTRATOR_ROLE" TO "WOLF" ;
GRANT "GSMADMIN_ROLE" TO "WOLF" ;
GRANT "AQ_USER_ROLE" TO "WOLF" ;
GRANT "JAVAUSERPRIV" TO "WOLF" ;
GRANT "XDB_SET_INVOKER" TO "WOLF" ;
GRANT "RECOVERY_CATALOG_OWNER" TO "WOLF" ;
GRANT "JAVA_ADMIN" TO "WOLF" ;
GRANT "DBFS_ROLE" TO "WOLF" ;
GRANT "PDB_DBA" TO "WOLF" ;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "WOLF" ;
GRANT "CDB_DBA" TO "WOLF" ;
GRANT "JAVASYSPRIV" TO "WOLF" ;
GRANT "HS_ADMIN_SELECT_ROLE" TO "WOLF" ;
GRANT "AUDIT_VIEWER" TO "WOLF" ;
GRANT "RESOURCE" TO "WOLF" ;
GRANT "DV_OWNER" TO "WOLF" ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "WOLF" ;
GRANT "EXECUTE_CATALOG_ROLE" TO "WOLF" ;
GRANT "DV_ACCTMGR" TO "WOLF" ;
GRANT "DV_REALM_OWNER" TO "WOLF" ;
GRANT "EXP_FULL_DATABASE" TO "WOLF" ;
GRANT "DV_STREAMS_ADMIN" TO "WOLF" ;
GRANT "JAVA_DEPLOY" TO "WOLF" ;
GRANT "SPATIAL_WFS_ADMIN" TO "WOLF" ;
GRANT "XS_NAMESPACE_ADMIN" TO "WOLF" ;
GRANT "XS_RESOURCE" TO "WOLF" ;
GRANT "ORDADMIN" TO "WOLF" ;
GRANT "AUTHENTICATEDUSER" TO "WOLF" ;
GRANT "CAPTURE_ADMIN" TO "WOLF" ;
GRANT "OEM_ADVISOR" TO "WOLF" ;
GRANT "XDBADMIN" TO "WOLF" ;
GRANT "EM_EXPRESS_BASIC" TO "WOLF" ;

-- SYSTEM PRIVILEGES

