export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};

export const CounterActionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
};

export const BasketActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  CHECKOUT: 'CHECKOUT',
  INIT_PRODUCTS: 'INIT_PRODUCTS'

}

export const UserActionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  UPDATE_MEMBER: "UPDATE_MEMBER",
  SET_BOUGHT_AMOUNT: "SET_BOUGHT_AMOUNT"
}

export const ProductActionTypes = {
  SELECT: "SELECT",
}