export const BasketActionTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  CHECKOUT: 'CHECKOUT',
  INIT_PRODUCTS: 'INIT_PRODUCTS'
}

export const UserActionTypes = {
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_ERROR : "LOGIN_ERROR",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  UPDATE_MEMBER: "UPDATE_MEMBER",
  SET_BOUGHT_AMOUNT: "SET_BOUGHT_AMOUNT"
}

export const ProductActionTypes = {
  SELECTED_PRODUCT: "SELECT_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}

export const WishlistActionTypes = {
  INIT_WISHLIST: "INIT_WISHLIST",
  CLEAR_WISHLIST: "CLEAR_WISHLIST_WISHLIST",
  ADD_PRODUCT: "ADD_PRODUCT_WISHLIST",
  REMOVE_PRODUCT: "REMOVE_PRODUCT_WISHLIST"
}